# TP1:  Learn numpy

## Constructeur de base: array et ses propriétés

In [2]:
# Importation du module numpy
import numpy as np

# creation d'un tableau allant de 7 à 100 avec un pas de 5
my_arr = np.arange(7, 100, 5)

# Affichage du tableau
print(my_arr)

# Affichage du type 
print(type(my_arr))

# Dimension
print(my_arr.shape)

# Taille
print(my_arr.size)


[ 7 12 17 22 27 32 37 42 47 52 57 62 67 72 77 82 87 92 97]
<class 'numpy.ndarray'>
(19,)
19


## 2 Constructeur d’initialisation des tableaux: zeros, ones, random, eye

In [16]:
# Tableau contenant que des zeros de taille 10
my_arr0 =  np.zeros(10, dtype = np.int8)
print(my_arr0)
print(my_arr0.shape)

# Tableau de dim 2D (4,5)
my_arr2d = np.zeros((4, 5), dtype = np.int8)
print(my_arr2d)
print(my_arr2d.shape)

# remplacement des 0 par des 1
my_arr2d = np.ones(my_arr2d.shape, dtype = np.int8)
print(my_arr2d)
print(my_arr2d.shape)

# Creation de la copie du tableau 
my_arr2d_cp = np.copy(my_arr2d)

# Replacement par 99 des valeurs du tableau 
my_arr2d_cp = np.full(my_arr2d_cp.shape, 99)
print(my_arr2d_cp)

# Creation d'un tableau à deux dimensions compris en [0, 1]
my_arr1d_rd = np.random.rand(1000, 3)

# Creation d'un tableau qui represente une simulation de 1000 lancers de 3 dés équilibrés à 6 faces numéroté de 1 à 6
my_arr2d_rd = np.random.randint(1, 7, (1000, 3))
print("Les 5 premières lignes et colonnes : ", my_arr2d_rd[:5])
print("Les 5 derniers lignes et colonnes : ", my_arr2d_rd[-5:])

# Matrice identité du même format que my_arr2d_rd
my_arr_id = np.eye(my_arr2d_rd.shape[0],my_arr2d_rd.shape[1])

print(my_arr_id.shape)
print(my_arr_id[:5])



[0 0 0 0 0 0 0 0 0 0]
(10,)
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
(4, 5)
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(4, 5)
[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]
Les 5 premières lignes et colonnes :  [[5 1 5]
 [5 4 5]
 [6 4 3]
 [6 5 3]
 [6 5 1]]
Les 5 derniers lignes et colonnes :  [[3 5 4]
 [1 5 4]
 [3 3 3]
 [5 1 2]
 [6 6 3]]
(1000, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Constructeurs linspace et arange

In [19]:
# Construction d'un tableau de taille 100 contenant les valeurs de 7 à 99
arr1 = np.linspace(7, 99, 100)
print(arr1)

# Construction d'un tableau allant de 7 à 99 de pas 5
arr2 = np.arange(7, 99, 5)
print(arr2)

# Type des tabeaux
print(type(arr1))
print(type(arr2))



[ 7.          7.92929293  8.85858586  9.78787879 10.71717172 11.64646465
 12.57575758 13.50505051 14.43434343 15.36363636 16.29292929 17.22222222
 18.15151515 19.08080808 20.01010101 20.93939394 21.86868687 22.7979798
 23.72727273 24.65656566 25.58585859 26.51515152 27.44444444 28.37373737
 29.3030303  30.23232323 31.16161616 32.09090909 33.02020202 33.94949495
 34.87878788 35.80808081 36.73737374 37.66666667 38.5959596  39.52525253
 40.45454545 41.38383838 42.31313131 43.24242424 44.17171717 45.1010101
 46.03030303 46.95959596 47.88888889 48.81818182 49.74747475 50.67676768
 51.60606061 52.53535354 53.46464646 54.39393939 55.32323232 56.25252525
 57.18181818 58.11111111 59.04040404 59.96969697 60.8989899  61.82828283
 62.75757576 63.68686869 64.61616162 65.54545455 66.47474747 67.4040404
 68.33333333 69.26262626 70.19191919 71.12121212 72.05050505 72.97979798
 73.90909091 74.83838384 75.76767677 76.6969697  77.62626263 78.55555556
 79.48484848 80.41414141 81.34343434 82.27272727 83.20

## 4 Manipulation des tableaux

In [52]:
# Construire deux tableaux A et B de format (3, 4) contenant des valeurs aléatoires qui suivent une loi normale centrée réduite

A = np.random.randn(3, 4)
B = np.random.randn(3, 4)
print(A)
print(B)

# Concaténer les tableaux A et B verticalement
C = np.vstack((A, B))
print(C)
print(C.shape)

# Concaténer les tableaux A et B horizontalement
C = np.hstack((A, B))
print(C)
print(C.shape)

# Utiliser la méthode concatenate pour concaténer les tableaux A et B verticalement ou horizontalement.
C = np.concatenate((A, B), axis = 0) # vertical
print(C.shape)
C = np.concatenate((A, B), axis = 1) # horizontal
print(C.shape)

# Utiliser la méthode reshape pour changer le format de tableau A en (6, 2).
A = np.reshape(A, (6,2))
print(A)

# Utiliser la méthode ravel pour vectoriser le tableau B.
B = np.ravel(B)

print(B)

[[ 0.08288113  0.67051692  1.4537499  -1.52579385]
 [-1.15248097 -0.03649023  0.44245237 -0.0405641 ]
 [ 0.99953707  1.70768754  1.26298903 -0.04268339]]
[[ 0.48497522  1.09794355 -2.55819493  1.60351316]
 [-1.43956482  0.49094374 -0.4265414  -1.14285969]
 [-1.633457   -0.87642338 -0.64987643  0.20840539]]
[[ 0.08288113  0.67051692  1.4537499  -1.52579385]
 [-1.15248097 -0.03649023  0.44245237 -0.0405641 ]
 [ 0.99953707  1.70768754  1.26298903 -0.04268339]
 [ 0.48497522  1.09794355 -2.55819493  1.60351316]
 [-1.43956482  0.49094374 -0.4265414  -1.14285969]
 [-1.633457   -0.87642338 -0.64987643  0.20840539]]
(6, 4)
[[ 0.08288113  0.67051692  1.4537499  -1.52579385  0.48497522  1.09794355
  -2.55819493  1.60351316]
 [-1.15248097 -0.03649023  0.44245237 -0.0405641  -1.43956482  0.49094374
  -0.4265414  -1.14285969]
 [ 0.99953707  1.70768754  1.26298903 -0.04268339 -1.633457   -0.87642338
  -0.64987643  0.20840539]]
(3, 8)
(6, 4)
(3, 8)
[[ 0.08288113  0.67051692]
 [ 1.4537499  -1.52579385]

# 5 Indexation et sélection
Il est possible d’accéder aux éléments d’un tableau grâce à l’indexation. Il se fait de la même manière avec Numpy qu’avec les listes en Python.

In [ ]:
# Création d'une matrice suivant une loi normale de moyenne 4 et de variance racine de 2
np.random.seed(7)
X = np.random.normal(loc=4, scale=np.sqrt(2), size=(10,7)) # mu = 4, signal = racine de 2
print(X)

# Afficher le premier et le dernier élément de X, i.e. x1,1 et x10,7.
print(X[0,0])
print(X[-1, -1])

# Afficher la première et la dernière colonne de X.
print(X[:, 0])
print(X[:, -1])

# Exécuter X[::3, ::3] et commenter.
print(X[::3, ::3]) # prendre une ligne sur trois et une colonne sur trois, en commençant à l'indice 0.

# Créer un tableau booléen mask vérifiant si les valeurs du tableau X sont supérieures à 4.
mask = X>4 
print(mask) 

# Créer un tableau booléen mask1 vérifiant si les valeurs du tableau X sont supérieures à 4 et inférieures à 6.
mask1 = (X>4) & (X <6)  
print(mask1) 

# Exécuter Y = X[mask] et Z = X[mask1].
Y = X[mask]
Z = X[mask1]

[[6.39076438 3.34106505 4.04641472 4.57631505 2.88429435 4.00292116
  3.9987408 ]
 [1.51844509 5.43918575 4.84923315 3.11550986 3.75739412 4.71460123
  3.63038621]
 [3.65670096 1.94480629 4.784295   4.17519406 4.38814495 1.8411683
  6.33444189]
 [4.21826341 3.45250144 6.86954145 3.93581446 1.94843051 3.42692127
  0.76383375]
 [5.48407083 3.41101637 2.94987073 5.51670181 1.66502651 4.75721146
  1.08047659]
 [3.06356528 2.29697596 6.06754576 6.49772867 3.5341386  5.18897635
  3.74546079]
 [4.80336083 2.93532743 1.58404353 1.45003342 4.54181612 7.17857941
  4.38100558]
 [3.25809703 6.70400301 4.33559549 4.14344932 4.35719886 3.81279037
  3.56233436]
 [1.9706552  4.70940364 3.86596727 5.68727829 3.47841192 1.30398586
  3.85912929]
 [6.40350869 3.45775782 2.74155236 2.31200612 2.51505199 3.57546195
  2.33125332]]
6.390764377854786
2.3312533200740093
[6.39076438 1.51844509 3.65670096 4.21826341 5.48407083 3.06356528
 4.80336083 3.25809703 1.9706552  6.40350869]
[3.9987408  3.63038621 6.33444

# 6 Somme lignes et colonnes


In [23]:
# Créer un tableau sumColX contenant la somme de chaque colonne de X.
sumColX = np.sum(X, axis=0)
print(sumColX)

# Créer un tableau sumRawX contenant la somme de chaque ligne de X.
sumRawX = np.sum(X, axis=1)
print(sumRawX)

# Calculer le minimum et maximum de chaque colonne de X.
minColX = np.min(X, axis=0)
maxColX = np.max(X, axis=0)
print(minColX, maxColX)

# Déterminer la position du minimum de chaque colonne de X.
posMinColX = np.argmin(X, axis=0)
print(posMinColX)

[40.7674317  37.69204276 42.09405946 41.41003106 33.06990793 39.80261736
 33.68706259]
[29.24051552 27.02475541 27.12475144 24.61530629 24.8643743  30.39439142
 26.87416631 30.17346844 24.87483148 23.33659224]
[1.51844509 1.94480629 1.58404353 1.45003342 1.66502651 1.30398586
 0.76383375] [6.40350869 6.70400301 6.86954145 6.49772867 4.54181612 7.17857941
 6.33444189]
[1 2 6 6 4 8 3]


## 7 Opérations mathématiques et statistiques

In [26]:
# Écrire une fonction qui renvoie un dictionnaire ayant pour clés le numéro de chaque colonne de X et
# pour valeurs un autre dictionnaire qui résume les agrégats suivants: moyenne, variance, écart type,
# médiane, de chaque colonne. 

def statsX(X: np.ndarray) -> dict:
    dicResumeX = {}
    meanColX = np.mean(X, axis=0)
    varColX = np.var(X, axis=0)
    stdColX = np.std(X, axis=0)
    medianColX = np.median(X, axis=0)
    
    for i in range(X.shape[1]):
        name = "column n° " + str(i+1)
        dicResumeX[name] = {
            'moyenne': meanColX[i],
            'variance': varColX[i],
            'std': stdColX[i],
            'median': medianColX[i],
            }
        
    return dicResumeX

dicResumeX = statsX(X)

print(dicResumeX)

{'column n° 1': {'moyenne': 4.076743170478842, 'variance': 2.6150746286834, 'std': 1.6171192376208379, 'median': 3.9374821840431027}, 'column n° 2': {'moyenne': 3.7692042755019592, 'variance': 1.8985992754196321, 'std': 1.377896685321375, 'median': 3.431758906018468}, 'column n° 3': {'moyenne': 4.209405946268099, 'variance': 2.206287173894517, 'std': 1.4853575912535395, 'median': 4.191005105242029}, 'column n° 4': {'moyenne': 4.141003105514786, 'variance': 2.170862732870811, 'std': 1.4733847877831545, 'median': 4.159321686973902}, 'column n° 5': {'moyenne': 3.3069907927463964, 'variance': 0.9428041472229234, 'std': 0.9709810231013392, 'median': 3.5062752621398596}, 'column n° 6': {'moyenne': 3.980261736200469, 'variance': 2.506991421473097, 'std': 1.5833481681149908, 'median': 3.9078557665348423}, 'column n° 7': {'moyenne': 3.3687062590247243, 'variance': 2.3803372685716626, 'std': 1.5428341675538764, 'median': 3.68792350166448}}


## 8 Algèbre linéaire

In [33]:
# Calculer Xtop la transposé de la matrice X. Vérifier le format de Xtop.
Xtop = X.T
print(Xtop.shape)

# A l’aide de la méthode dot, calculer le produit matriciel 
P = X.T @ X
print(P.shape)

# Utiliser la méthode np.linalg.eig pour calculer les valeurs et vecteurs propres
eig = np.linalg.eig(P)
print(eig)

# Calculer la décomposition de la valeur singulière de X à l’aide de la méthode np.linalg.svd
U, s, Vtop = np.linalg.svd(X,full_matrices=False)
print(U.shape)
print(s.shape)
print(Vtop.shape)

# On vérifie que les matrices U et V sont des matrices unitaires,
np.set_printoptions(precision=2)
print(U.T.dot(U), sep=2 * '\n')
print(Vtop.T.dot(Vtop), sep=2 * '\n')

(7, 10)
(7, 7)
EigResult(eigenvalues=array([1.04558484e+03, 4.96915031e+01, 3.69549429e+01, 2.54641930e+01,
       4.95179604e-01, 1.66445978e+01, 1.05802539e+01]), eigenvectors=array([[ 0.39495424, -0.60189905, -0.34576266, -0.35373154,  0.05667722,
         0.43871839,  0.20338321],
       [ 0.36836564,  0.1334712 ,  0.08183311,  0.72432789, -0.18637697,
         0.52941111, -0.01149549],
       [ 0.41457772,  0.43521549, -0.32128844, -0.01385051, -0.05340949,
        -0.33429377,  0.64860604],
       [ 0.40830133,  0.38094731, -0.3720178 , -0.22805333,  0.0616912 ,
        -0.00415978, -0.70280901],
       [ 0.32542034,  0.04691145,  0.45314271, -0.00681395,  0.82705716,
        -0.00674042,  0.04946909],
       [ 0.39141399, -0.51825068,  0.07171398,  0.31332438, -0.15440462,
        -0.64022099, -0.20291021],
       [ 0.33261079,  0.12076899,  0.64934337, -0.4469948 , -0.49752246,
         0.07451222,  0.01590859]]))
(10, 7)
(7,)
(7, 7)
[[ 1.00e+00 -1.80e-16  8.63e-17 -1.40e-16 -1