# TP1:  Learn numpy

## Constructeur de base: array et ses propriétés

In [3]:
# Importation du module numpy
import numpy as np

# creation d'un tableau allant de 7 à 100 avec un pas de 5
my_arr = np.arange(7, 100, 5)

# Affichage du tableau
print(my_arr)

# Affichage du type 
print(type(my_arr))

# Dimension
print(my_arr.shape)

# Taille
print(my_arr.size)


[ 7 12 17 22 27 32 37 42 47 52 57 62 67 72 77 82 87 92 97]
<class 'numpy.ndarray'>
(19,)
19


## 2 Constructeur d’initialisation des tableaux: zeros, ones, random, eye

In [ ]:
# Tableau contenant que des zeros de taille 10
my_arr0 =  np.zeros(10, dtype = np.int8)
print(my_arr0)
print(my_arr0.shape)

# Tableau de dim 2D (4,5)
my_arr2d = np.zeros((4, 5), dtype = np.int8)
print(my_arr2d)
print(my_arr2d.shape)

# remplacement des 0 par des 1
my_arr2d = np.ones(my_arr2d.shape, dtype = np.int8)
print(my_arr2d)
print(my_arr2d.shape)

# Creation de la copie du tableau 
my_arr2d_cp = np.copy(my_arr2d)

# Replacement par 99 des valeurs du tableau 
my_arr2d_cp = np.full(my_arr2d_cp.shape, 99)
print(my_arr2d_cp)

# Creation d'un tableau à deux dimensions compris en [0, 1]
my_arr1d_rd = np.random.rand(1000, 3)

# Creation d'un  



[0 0 0 0 0 0 0 0 0 0]
(10,)
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
(4, 5)
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(4, 5)
[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]
